"use client";

import { motion } from "framer-motion";
import { 
  Users, 
  Share2 as Twitter, 
  Send, 
  Code as Github, 
  Trophy, 
  Share2, 
  ArrowRight,
  TrendingUp,
  UserPlus,
  Target
} from "lucide-react";
import StatsCard from "@/components/StatsCard";

export default function CommunityPage() {
  const leaderboard = [
    { rank: 1, user: "crypto_king", earnings: "125,400 EFX", tasks: 842, avatar: "👑" },
    { rank: 2, user: "web3_pioneer", earnings: "98,200 EFX", tasks: 621, avatar: "🚀" },
    { rank: 3, user: "alpha_earner", earnings: "84,500 EFX", tasks: 512, avatar: "🔥" },
    { rank: 4, user: "earnify_pro", earnings: "72,100 EFX", tasks: 489, avatar: "💎" },
    { rank: 5, user: "task_master", earnings: "65,400 EFX", tasks: 412, avatar: "⚡" },
  ];

  const socialChannels = [
    { name: "Twitter / X", handle: "@earnifyx", followers: "45k+", icon: Twitter, color: "hover:text-blue-400" },
    { name: "Telegram", handle: "t.me/earnifyxtoken", followers: "28k+", icon: Send, color: "hover:text-blue-500", href: "https://t.me/earnifyxtoken" },
    { name: "Discord", handle: "discord.gg/earnifyx", followers: "32k+", icon: Share2, color: "hover:text-indigo-500" },
    { name: "GitHub", handle: "earnifyx-protocol", followers: "1.2k+", icon: Github, color: "hover:text-gray-400" },
  ];

  return (
    <div className="container mx-auto px-6 py-12">
      <div className="flex flex-col gap-24">
        {/* Hero */}
        <section className="text-center max-w-3xl mx-auto">
          <h1 className="text-5xl font-black mb-6">EarnifyX <span className="neon-text">Community</span></h1>
          <p className="text-xl text-foreground/60 leading-relaxed">
            Join the global movement of decentralized earners. Connect, share strategies, and compete for the top spot on the leaderboard.
          </p>
        </section>

        {/* Stats */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          <StatsCard label="Community Members" value="125,000+" icon={Users} trend="+1.2k today" isPositive />
          <StatsCard label="Referral Payouts" value="2.4M EFX" icon={Share2} />
          <StatsCard label="Countries Reached" value="142" icon={TrendingUp} />
          <StatsCard label="Active Ambassadors" value="850" icon={Trophy} />
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
          {/* Referral System */}
          <section className="flex flex-col gap-8">
            <div className="glass-card p-10 border border-primary/20 bg-primary/5 h-full">
              <h2 className="text-3xl font-bold mb-6 flex items-center gap-3">
                <UserPlus className="text-primary" />
                Referral Hub
              </h2>
              <p className="text-foreground/60 mb-8 leading-relaxed text-lg">
                Earn 10% lifetime commission on all rewards generated by your direct referrals, and 5% from their referrals. Growth is rewarded.
              </p>
              
              <div className="space-y-6 mb-10">
                <div className="flex justify-between items-center p-4 glass rounded-xl border border-white/5">
                  <div className="text-sm font-bold text-foreground/40 uppercase tracking-widest">Your Referral Link</div>
                  <button className="text-primary font-bold hover:underline">Copy Link</button>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="p-4 glass rounded-xl border border-white/5">
                    <p className="text-xs text-foreground/40 font-bold mb-1">Direct Referrals</p>
                    <p className="text-2xl font-black">124</p>
                  </div>
                  <div className="p-4 glass rounded-xl border border-white/5">
                    <p className="text-xs text-foreground/40 font-bold mb-1">Referral Earnings</p>
                    <p className="text-2xl font-black text-primary">1,450 <span className="text-xs font-medium">EFX</span></p>
                  </div>
                </div>
              </div>

              <button className="btn-primary w-full py-4 text-lg flex items-center justify-center gap-2">
                Generate Custom Link
                <ArrowRight size={20} />
              </button>
            </div>
          </section>

          {/* Social Channels */}
          <section className="flex flex-col gap-8">
             <div className="glass-card p-10 border border-white/5 h-full">
                <h2 className="text-3xl font-bold mb-8">Join the Conversation</h2>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                  {socialChannels.map((channel, i) => (
                    <motion.a 
                      key={i}
                      href={channel.href || "#"}
                      whileHover={{ scale: 1.02 }}
                      className={`glass p-6 rounded-2xl border border-white/10 flex flex-col gap-4 transition-all ${channel.color}`}
                    >
                      <div className="flex justify-between items-start">
                        <channel.icon size={28} />
                        <span className="text-xs font-bold text-foreground/40">{channel.followers}</span>
                      </div>
                      <div>
                        <p className="font-bold text-lg">{channel.name}</p>
                        <p className="text-sm text-foreground/50">{channel.handle}</p>
                      </div>
                    </motion.a>
                  ))}
                </div>
             </div>
          </section>
        </div>

        {/* Leaderboard */}
        <section className="glass-card p-10 border border-white/5 overflow-hidden relative">
          <div className="absolute top-0 right-0 p-8 opacity-10">
            <Trophy size={200} />
          </div>
          <div className="relative z-10">
            <div className="flex justify-between items-center mb-12">
              <div>
                <h2 className="text-3xl font-bold mb-2">Protocol <span className="text-primary">Leaderboard</span></h2>
                <p className="text-foreground/60">The top earners in the EarnifyX ecosystem this month.</p>
              </div>
              <div className="hidden sm:flex gap-4">
                <button className="glass px-4 py-2 rounded-xl text-sm font-bold">Monthly</button>
                <button className="btn-primary px-4 py-2 rounded-xl text-sm font-bold">All-Time</button>
              </div>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left">
                <thead>
                  <tr className="border-b border-white/5">
                    <th className="pb-6 text-xs font-bold text-foreground/40 uppercase tracking-[0.2em]">Rank</th>
                    <th className="pb-6 text-xs font-bold text-foreground/40 uppercase tracking-[0.2em]">User</th>
                    <th className="pb-6 text-xs font-bold text-foreground/40 uppercase tracking-[0.2em]">Tasks</th>
                    <th className="pb-6 text-xs font-bold text-foreground/40 uppercase tracking-[0.2em] text-right">Total Earnings</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/5">
                  {leaderboard.map((user, i) => (
                    <tr key={i} className="group hover:bg-white/[0.02] transition-all">
                      <td className="py-6">
                        <div className={`w-8 h-8 rounded-lg flex items-center justify-center font-bold ${
                          user.rank === 1 ? "bg-amber-500/20 text-amber-500" : 
                          user.rank === 2 ? "bg-gray-300/20 text-gray-300" :
                          user.rank === 3 ? "bg-amber-700/20 text-amber-700" : "bg-white/5"
                        }`}>
                          {user.rank}
                        </div>
                      </td>
                      <td className="py-6">
                        <div className="flex items-center gap-3">
                          <span className="text-2xl">{user.avatar}</span>
                          <span className="font-bold group-hover:text-primary transition-colors">{user.user}</span>
                        </div>
                      </td>
                      <td className="py-6 text-foreground/60 font-medium">{user.tasks} tasks</td>
                      <td className="py-6 text-right">
                        <span className="text-lg font-black text-primary">{user.earnings}</span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <div className="mt-8 text-center">
              <button className="text-primary font-bold hover:underline flex items-center gap-2 mx-auto">
                View Full Leaderboard
                <ArrowRight size={16} />
              </button>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
